apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fred
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/freddie-entity/argocd-app-config.git
    targetRevision: HEAD
    path: nodeapp
  destination: 
    server: https://kubernetes.default.svc
    namespace: nsnodeapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true